CREATE DATABASE BeatSync;
USE BeatSync;

CREATE TABLE usuarios (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	data_nasc DATE NOT NULL,
	genero VARCHAR(255) NOT NULL,
	senha INT NOT NULL
);
